- hosts: kafka
  remote_user: kafka
  sudo: yes

  tasks:
  - name: Update repositories cache and install default-jre
    apt:
      name: default-jre
      update_cache: yes

  - name: Install zookeeperd
    apt:
      name: zookeeperd

  - name: Download kafka
    command: wget "http://mirror.cc.columbia.edu/pub/software/apache/kafka/0.8.2.1/kafka_2.11-0.8.2.1.tgz" -O kafka.tgz
    args:
      chdir: /tmp

  - name: Making directory for kafka
    file:
      path: /home/kafka/kafka
      state: directory
      mode: 0755

  - name: Extract kafka
    command: tar -xvzf /tmp/kafka.tgz --strip 1
    args:
      chdir: /home/kafka/kafka

  - name: Copy config
    template: src=server.properties.j2  dest=/home/kafka/kafka/config/server.properties

  - name: Edit config
    command: echo 'delete.topic.enable = true' >> /home/kafka/kafka/config/server.properties

  - name: Start kafka
    command: nohup ~/kafka/bin/kafka-server-start.sh ~/kafka/config/server.properties > ~/kafka/kafka.log 2>&1 &
